const fs = require('fs');
const path = require('path');

// Configuration
const MATH_CORE_PATH = path.join(__dirname, '../src/shared/KaioaMath.ts');
const TILED_VIEW_PATH = path.join(__dirname, 'tiled_extensions/kaioa_engine_view.js');
const OUTPUT_PATH = path.join(__dirname, 'tiled_extensions/kaioa_engine_bundled.js');

console.log("Building KaioaEngine for Tiled...");

// 1. Read Math Core & Transpile to simple JS
let mathCore = fs.readFileSync(MATH_CORE_PATH, 'utf8');

// --- SURGICAL TRANSPILATION ---
// Regex creates bugs. We use explicit replacement for known types.

// Remove Interfaces
mathCore = mathCore.replace(/export interface [\w]+ \{[^}]+\}/g, '');

// Remove Class Export
mathCore = mathCore.replace(/export class/, 'class');

// Explicit Type Removal (Whack-a-mole, but safe)
mathCore = mathCore.replace(/: Rect/g, '');
mathCore = mathCore.replace(/: Point\[\]/g, '');
mathCore = mathCore.replace(/: Point/g, '');
mathCore = mathCore.replace(/: number/g, '');
mathCore = mathCore.replace(/: boolean/g, '');
mathCore = mathCore.replace(/: string/g, '');

// Remove Return Types
mathCore = mathCore.replace(/\): Point\[\]/g, ')');
mathCore = mathCore.replace(/\): boolean/g, ')');
mathCore = mathCore.replace(/\): number/g, ')');
mathCore = mathCore.replace(/\): any/g, ')'); // Fix for getEntityCollider
mathCore = mathCore.replace(/\): \{ [^}]* \}/g, ')'); // Handles complex return types like getEntityCollider

// Remove leftover 'export'
mathCore = mathCore.replace(/export /g, '');

// 2. Read Game Config
const configPath = path.join(__dirname, '../assets/data/kaioa_config.json');
// Robust path escaping for Windows
const safeConfigPath = configPath.replace(/\\/g, '/'); 
const gameConfigRaw = fs.readFileSync(configPath, 'utf8');

// Validate JSON before injecting
try {
    JSON.parse(gameConfigRaw);
} catch (e) {
    console.error("ERROR: kaioa_config.json is invalid JSON. Build aborted.");
    process.exit(1);
}

const configInjection = `
// INJECTED CONFIGURATION
const KAIOA_CONFIG = ${gameConfigRaw};
const KAIOA_PROJECT_CONFIG_PATH = "${safeConfigPath}";
\n`;

// 3. Read Tiled View Logic
let tiledView = fs.readFileSync(TILED_VIEW_PATH, 'utf8');

// 4. Inject Core & Config
const BUNDLE_HEADER = `/** 
 * KAIOA ENGINE BUNDLED EXTENSION 
 * Auto-generated by tools/build_kaioa.js 
 * DO NOT EDIT DIRECTLY 
 */\n\n`;

tiledView = tiledView.replace(
    /\/\/ --- MATH UTILS[\s\S]*?function projectShadow[\s\S]*?return \[bl, \{x: tlX, y: tlY\}, \{x: trX, y: trY\}, br\];\n\}/, 
    `// Math Utils provided by KaioaMath class below`
);

tiledView = tiledView.replace(/projectShadow\(/g, 'KaioaMath.calculateShadowProjection(');

// Add Alert for Debugging
const debugFooter = `\ntiled.log("KaioaEngine Booted Successfully.");`;

const finalScript = BUNDLE_HEADER + configInjection + mathCore + "\n\n" + tiledView + debugFooter;

fs.writeFileSync(OUTPUT_PATH, finalScript);
console.log(`Success! Bundled extension written to: ${OUTPUT_PATH}`);
console.log("-> Please copy this file to your Tiled Extensions folder.");
