const fs = require('fs');
const path = require('path');

const MAP_PATH = path.join(__dirname, '../assets/maps/world.json');
const TYPES_PATH = path.join(__dirname, '../src/shared/generated/MapTypes.ts');
const TYPES_DIR = path.dirname(TYPES_PATH);

if (!fs.existsSync(TYPES_DIR)) {
    fs.mkdirSync(TYPES_DIR, { recursive: true });
}

function generateTypes() {
    console.log('[MapWatcher] Analyzing map for types...');
    
    try {
        const raw = fs.readFileSync(MAP_PATH, 'utf8');
        const map = JSON.parse(raw);
        
        const zoneNames = new Set();
        const locations = new Set();

        // Recursively find layers
        const scanLayers = (layers) => {
            if (!layers) return;
            layers.forEach(layer => {
                if (layer.type === 'objectgroup') {
                    layer.objects.forEach(obj => {
                        if (obj.name) {
                            if (layer.name === 'Logic' || obj.type === 'zone') {
                                zoneNames.add(obj.name);
                            }
                            locations.add(obj.name);
                        }
                    });
                }
                if (layer.layers) scanLayers(layer.layers);
            });
        };

        scanLayers(map.layers);

        const zones = Array.from(zoneNames).map(z => `"${z}"`).join(' | ') || '"UNKNOWN"';
        const locs = Array.from(locations).map(l => `"${l}"`).join(' | ') || '"UNKNOWN"';

        const content = `// Auto-generated by tools/watch_map.js
// Do not edit directly. Changes in Tiled will overwrite this.

export type MapZone = ${zones};
export type MapLocation = ${locs};
`;

        fs.writeFileSync(TYPES_PATH, content);
        console.log(`[MapWatcher] Generated ${TYPES_PATH}`);

    } catch (e) {
        console.error('[MapWatcher] Error:', e.message);
    }
}

// Run once
generateTypes();

// If run with --watch flag
if (process.argv.includes('--watch')) {
    console.log('[MapWatcher] Watching for changes...');
    fs.watch(MAP_PATH, (eventType) => {
        if (eventType === 'change') {
            // Debounce slightly
            setTimeout(generateTypes, 100);
        }
    });
}
